query AuctionDetailSubgraph($auctionId: BigInt!, $bidLimit: Int!) {
  createdAuction: auctionCreateds(
    first: 1
    orderBy: blockTimestamp
    orderDirection: desc
    where: { auctionId: $auctionId }
  ) {
    auctionId
    seller
    externalMarketId
    endTime
    blockTimestamp
  }
  bids: bidPlaceds(
    first: $bidLimit
    orderBy: blockTimestamp
    orderDirection: desc
    where: { auctionId: $auctionId }
  ) {
    bidAmount
    previousBid
    blockTimestamp
    transactionHash
  }
  closedAuction: auctionCloseds(
    first: 1
    orderBy: blockTimestamp
    orderDirection: desc
    where: { auctionId: $auctionId }
  ) {
    seller
    winningBid
    externalMarketId
    blockTimestamp
  }
  forceClosedAuction: auctionForceCloseds(
    first: 1
    orderBy: blockTimestamp
    orderDirection: desc
    where: { auctionId: $auctionId }
  ) {
    seller
    refundAmount
    externalMarketId
    reputationDelta
    blockTimestamp
  }
  reputationUpdates: reputationUpdateds(
    orderBy: blockTimestamp
    orderDirection: desc
    where: { auctionId: $auctionId }
  ) {
    delta
    newScore
    blockTimestamp
  }
}
