query AuctionDetailSubgraph(
  $auctionId: ID!
  $auctionIdBigInt: BigInt!
  $bidLimit: Int!
) {
  auction(id: $auctionId) {
    auctionId
    sellerId
    eventId
    eventTitle
    endTime
    bidCount
    currentBid
    status
    predictionOutcome
    scoreChange
    blockTimestamp
    seller {
      reputationScore
      totalAuctionCount
      totalEarnings
      auctionsWithCorrectPredictionsCount
      auctionsWithWrongPredictionsCount
    }
  }
  bids: bidPlaceds(
    first: $bidLimit
    orderBy: blockTimestamp
    orderDirection: desc
    where: { auctionId: $auctionIdBigInt }
  ) {
    bidAmount
    previousBid
    blockTimestamp
    transactionHash
  }
  closedAuction: auctionCloseds(
    first: 1
    where: { auctionId: $auctionIdBigInt }
  ) {
    winningBid
    blockTimestamp
  }
  cancelledAuction: auctionCancelleds(
    first: 1
    where: { auctionId: $auctionIdBigInt }
  ) {
    blockTimestamp
  }
  reputationUpdates: sellerReputationScoreUpdateds(
    orderBy: blockTimestamp
    orderDirection: desc
    where: { auctionId: $auctionIdBigInt }
  ) {
    predictionOutcome
    scoreChange
    newScore
    blockTimestamp
  }
}
