query RecentAuctions {
  auctionCreateds(first: 10, orderBy: blockTimestamp, orderDirection: desc) {
    id
    auctionId
    sellerId
    eventId
    endTime
    blockTimestamp
    transactionHash
  }
}

query RecentBids {
  bidPlaceds(first: 10, orderBy: blockTimestamp, orderDirection: desc) {
    id
    auctionId
    bidAmount
    previousBid
    blockTimestamp
    transactionHash
  }
}

query RecentClosedAuctions {
  auctionCloseds(first: 10, orderBy: blockTimestamp, orderDirection: desc) {
    id
    auctionId
    seller
    winningBid
    externalMarketId
    blockTimestamp
    transactionHash
  }
}

query RecentForceClosedAuctions {
  auctionForceCloseds(first: 10, orderBy: blockTimestamp, orderDirection: desc) {
    id
    auctionId
    sellerId
    heldAmount
    eventId
    reputationDelta
    blockTimestamp
    transactionHash
  }
}
