query RecentAuctions {
  auctionCreateds(first: 10, orderBy: blockTimestamp, orderDirection: desc) {
    id
    auctionId
    seller
    reservePrice
    endTime
    blockTimestamp
    transactionHash
  }
}

query RecentBids {
  bidPlaceds(first: 10, orderBy: blockTimestamp, orderDirection: desc) {
    id
    auctionId
    bidder
    bidAmount
    blockTimestamp
    transactionHash
  }
}

query RecentClosedAuctions {
  auctionCloseds(first: 10, orderBy: blockTimestamp, orderDirection: desc) {
    id
    auctionId
    buyer
    seller
    winningBid
    externalMarketId
    blockTimestamp
    transactionHash
  }
}

query RecentForceClosedAuctions {
  auctionForceCloseds(first: 10, orderBy: blockTimestamp, orderDirection: desc) {
    id
    auctionId
    seller
    refundedBidder
    refundAmount
    reputationDelta
    blockTimestamp
    transactionHash
  }
}
