query HomepageAuctions(
  $limit: Int!
  $skip: Int!
  $where: Auction_filter
  $orderBy: Auction_orderBy
  $orderDirection: OrderDirection
) {
  auctions(
    first: $limit
    skip: $skip
    orderBy: $orderBy
    orderDirection: $orderDirection
    where: $where
  ) {
    auctionId
    sellerId
    eventId
    eventTitle
    endTime
    bidCount
    currentBid
    status
    seller {
      reputationScore
      totalAuctionCount
      auctionsWithCorrectPredictionsCount
      auctionsWithWrongPredictionsCount
    }
  }
}
