query HomepageAuctionLists(
  $currentTimestamp: BigInt!
  $openLimit: Int!
  $closedLimit: Int!
) {
  openAuctions: auctionCreateds(
    first: $openLimit
    orderBy: endTime
    orderDirection: asc
    where: { endTime_gt: $currentTimestamp }
  ) {
    id
    auctionId
    sellerId
    eventId
    eventTitle
    endTime
    blockTimestamp
    transactionHash
  }
  closedAuctions: auctionCloseds(
    first: $closedLimit
    orderBy: blockTimestamp
    orderDirection: desc
  ) {
    id
    auctionId
    sellerId
    winningBid
    eventId
    blockTimestamp
    transactionHash
  }
}

query HomepageClosedAuctionReferences($auctionIds: [BigInt!]) {
  referenceAuctions: auctionCreateds(where: { auctionId_in: $auctionIds }) {
    id
    auctionId
    sellerId
    eventId
    eventTitle
    endTime
    blockTimestamp
    transactionHash
  }
}

query HomepageLatestBid($auctionId: BigInt!) {
  bidPlaceds(
    first: 1
    orderBy: blockTimestamp
    orderDirection: desc
    where: { auctionId: $auctionId }
  ) {
    id
    auctionId
    bidAmount
  }
}
