import "server-only";

import type { Address } from "viem";
import {
  EXAMPLE_PREDICTION_MARKET_ADDRESS as DEFAULT_EXAMPLE_PREDICTION_MARKET_ADDRESS,
  SECRET_MARKETPLACE_ADDRESS as DEFAULT_SECRET_MARKETPLACE_ADDRESS,
} from "@private-streams/common";
import { env } from "@/env";

export const SECRET_MARKETPLACE_ADDRESS = (env.SECRET_MARKETPLACE_ADDRESS ??
  DEFAULT_SECRET_MARKETPLACE_ADDRESS) as Address;

export const EXAMPLE_PREDICTION_MARKET_ADDRESS = (env.EXAMPLE_PREDICTION_MARKET_ADDRESS ??
  DEFAULT_EXAMPLE_PREDICTION_MARKET_ADDRESS) as Address;
